# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: ReliableWebApp
version: 1.0.0
summary: Reliable Web App regional infrastructure
description: Deploys the Reliable Web App to one region
runner: ARM
templatePath: azuredeploy.json

# parameters:
# - id: "name"
#   name: "name"
#   description: "Deployment unique name"
#   type: "string"
#   required: true
# - id: "principalId"
#   name: "principalId"
#   description: "Principal ID of the service principal used to deploy the infrastructure"
#   type: "string"
#   default: "b0c31f35-a15e-4bea-ae85-961ae07a5d14"
#   required: true
# - id: "isProd"
#   name: "isProd"
#   description: "Is this a production environment?"
#   type: "string"
#   required: true
#   default: "false"
# - id: "secondaryAzureLocation"
#   name: "secondaryAzureLocation"
#   description: "Secondary Azure location"
#   type: "string"
#   required: true
#   default: "westeurope"
# - id: "azureSqlPassword"
#   name: "azureSqlPassword"
#   description: "Azure SQL password"
#   type: "string"
#   required: true
# - id: "principalType"
#   name: "principalType"
#   description: "Principal type of the service principal used to deploy the infrastructure"
#   type: "string"
#   required: true
#   default: "User"
# - id: "azureAdApiScopeFrontEnd"
#   name: "azureAdApiScopeFrontEnd"
#   description: "Azure AD API scope for the front end"
#   type: "string"
#   required: true
#   default: "api://b0c31f35-a15e-4bea-ae85-961ae07a5d14/ReliableWebApp.FrontEnd"
# - id: "azureAdClientIdForBackEnd"
#   name: "azureAdClientIdForBackEnd"
#   description: "Azure AD client ID for the back end"
#   type: "string"
#   required: true
#   default: "b0c31f35-a15e-4bea-ae85-961ae07a5d14"
# - id: "azureAdClientIdForFrontEnd"
#   name: "azureAdClientIdForFrontEnd"
#   description: "Azure AD client ID for the front end"
#   type: "string"
#   required: true
#   default: "b0c31f35-a15e-4bea-ae85-961ae07a5d14"
# - id: "azureAdClientSecretForFrontEnd"
#   name: "azureAdClientSecretForFrontEnd"
#   description: "Azure AD client secret for the front end"
#   type: "string"
#   required: true
# - id: "azureAdTenantId"
  name: "azureAdTenantId"
  description: "Azure AD tenant ID"
  type: "string"
  required: true
  default: "b0c31f35-a15e-4bea-ae85-961ae07a5d14"