# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: ReliableWebApp
version: 1.0.0
summary: Reliable Web App regional infrastructure
description: Deploys the Reliable Web App to one region
runner: ARM
templatePath: azuredeploy.json

parameters:
- id: name
  name: Name
  description: 'Deployment unique name'
  type: string
  required: true

- id: principalId
  name: 'Principal Id'
  description: 'Principal ID of the service principal used to deploy the infrastructure'
  type: string
  # required: true
  default: b0c31f35-a15e-4bea-ae85-961ae07a5d14

- id: isProd
  name: 'is Prod?'
  description: 'Is this a production environment?'
  type: boolean

- id: secondaryAzureLocation
  name: 'Secondary Azure Location'
  description: 'Secondary Azure location'
  type: string
  allowed:
    - 'westus2'
    - 'westeurope'
    - 'northcentralus'
    - 'northeurope'
  default: 'westeurope'

- id: principalType
  name: 'Principal Type'
  description: 'Principal type of the service principal used to deploy the infrastructure'
  type: string
  default: User

- id: azureAdApiScopeFrontEnd
  name: 'AzureAD Api Scope Frontend'
  description: 'Azure AD API scope for the front end'
  type: string
  # required: true
  default: 'api://b0c31f35-a15e-4bea-ae85-961ae07a5d14/ReliableWebApp.FrontEnd'

- id: azureAdClientIdForBackEnd
  name: 'AzureAD Client Id for Backend'
  description: 'Azure AD client ID for the back end'
  type: string
  # required: true
  default: b0c31f35-a15e-4bea-ae85-961ae07a5d14

- id: azureAdClientIdForFrontEnd
  name: 'AzureAD ClientId for Frontend'
  description: 'Azure AD client ID for the front end'
  type: string
  # required: true
  default: b0c31f35-a15e-4bea-ae85-961ae07a5d14

- id: 'AzureAD Client Secret for Frontend'
  name: azureAdClientSecretForFrontEnd
  description: 'Azure AD client secret for the front end'
  type: string
  # required: true
  default: secret

- id: 'AzureAD Tenant Id'
  name: azureAdTenantId
  description: 'Azure AD tenant ID'
  type: string
  # required: true
  default: b0c31f35-a15e-4bea-ae85-961ae07a5d14