name: Build Apps
on: 
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'

permissions:
  id-token: write
  contents: read
  
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-7.0.x
        path: TestResults-7.0.x
      if: ${{ always() }}
