name: Build Apps
on: 
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'

permissions:
  id-token: write
  contents: read
  
jobs: 
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install dependencies
      working-directory: ./src
      run: dotnet restore

    - name: Build
      working-directory: ./src
      run: dotnet build --configuration Release --no-restore

    - name: Test
      working-directory: ./src
      run: dotnet test --no-restore --verbosity normal

    - name: Publish
      working-directory: ./src
      run: dotnet publish --configuration Release --no-build --no-restore --output /publish

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Application_Artifact
        path: /pubish