name: Release
on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

permissions:
  id-token: write
  contents: read
  
jobs: 
  build-test-package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Install dependencies
      working-directory: src
      run: dotnet restore

    - name: Build
      working-directory: src
      run: dotnet build --configuration Release --no-restore

    - name: Test
      working-directory: src
      run: dotnet test --no-restore --verbosity normal

    - name: Publish FrontEnd
      working-directory: src/Relecloud.Web
      run: dotnet publish --configuration Release --no-build --no-restore --output ../../publish/frontend

    - name: Create Zip File
      uses: papeloto/action-zip@v1
      with:
        files: publish/frontend
        dest: publish/frontend.zip
    
    - name: Upload Build Artifact FrontEnd
      uses: actions/upload-artifact@v3
      with:
        name: FrontEnd_Artifact
        path: publish/frontend.zip

    - name: Publish API
      working-directory: src/Relecloud.Web.Api
      run: dotnet publish --configuration Release --no-build --no-restore --output ../../publish/api

    - name: Create Zip File
      uses: papeloto/action-zip@v1
      with:
        files: publish/api
        dest: publish/api.zip
 
    - name: Upload Build Artifact API
      uses: actions/upload-artifact@v3
      with:
        name: API_Artifact
        path: publish/api.zip

  deploy-to-test:
    runs-on: ubuntu-latest
    needs: build-test-package
    environment: test
    steps:
      - name: Azure Login (Federated)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download Frontend Artifact
        uses: actions/download-artifact@v3
        with:
          name: FrontEnd_Artifact
          path: publish

      - name: Deploy to Frontend to Test
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ vars.FRONTEND_APP }}
          package: publish/frontend.zip

      - name: Download Api Artifact
        uses: actions/download-artifact@v3
        with:
          name: API_Artifact
          path: publish

      - name: Deploy to Api to Test
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ vars.API_APP }}
          package: publish/api.zip

      # execute playwright tests here 
      #- name: UI Tests
      
  deploy-to-production:
    runs-on: ubuntu-latest
    needs: deploy-to-test
    environment: production
    steps:
      - name: Azure Login (Federated)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download FrontEnd Artifact
        uses: actions/download-artifact@v2
        with:
          name: FrontEnd_Artifact
          path: publish

      - name: Deploy FrontEnd to Production
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ vars.FRONTEND_APP }} 
          package: publish/frontend.zip

      - name: Download API Artifact
        uses: actions/download-artifact@v2
        with:
          name: API_Artifact
          path: publish

      - name: Deploy API to Production
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ vars.API_APP }} 
          package: publish/api.zip
          
    


   